### ISSUE TITLE
Correct hex points calculation in utils.py

### ISSUE THREAD

**Issue by AChorostian** [HEX-CLAN/PyBattle#1]

**Comment by AChorostian** [comment]
points should be integers for better pattern repeatability

**Comment by malinowskikam** [comment]
![image](https://user-images.githubusercontent.com/32635788/66526310-78bdbb80-eaf8-11e9-994a-b10faffefdab.png)
![image](https://user-images.githubusercontent.com/32635788/66526505-3648ae80-eaf9-11e9-90e0-81d68ba31849.png)

**Comment by malinowskikam** [comment]
we can use this to map only hex center, and then draw the rest of it roughly

**Comment by AChorostian** [comment]
looks good, but remember to rotate this map by 90 degrees to match the original game ;)
