### ISSUE TITLE
Add menu to the game

### ISSUE THREAD

**Issue by AChorostian** [HEX-CLAN/PyBattle#2]

**Comment by jmalinwsk** [comment]
is it going to be possible to play at full resolution or change the window size manually?

**Comment by AChorostian** [comment]
Manual resizing is possible right now. The fullscreen option will be added to settings later.

**Comment by jmalinwsk** [comment]
> Manual resizing is possible right now. The fullscreen option will be added to settings later.

I moved the topic of resizing window to another issue. [Issue #11 Fix the appearance of components during resizing the window](https://github.com/HEX-CLAN/PyBattle/issues/11)

**Comment by jmalinwsk** [comment]
coding the menu has been completed.

![image](https://user-images.githubusercontent.com/37940924/67428547-a3227500-f5de-11e9-99a3-263b866c84c7.png)
