### ISSUE TITLE
Add procedural map generator

### ISSUE THREAD

**Issue by AChorostian** [HEX-CLAN/PyBattle#3]
The minimal goal is to prepare a map generator for one land unit and five 5 water units (deep dependent)
like in the original map:
![image](https://user-images.githubusercontent.com/25078869/66603888-5a65c780-ebad-11e9-9fa0-c905095fee96.png)

**Comment by malinowskikam** [comment]
Any ideas how much data we need stored by gamemap?
Map: cells, ?
cell: type, structure, armies ?

**Comment by AChorostian** [comment]
I think it doesn't matter right now how much data we need to store. I think it is not connected with terrain generation.

**Comment by AChorostian** [comment]
the basic generator is already implemented
